# Generated by Django 2.1.1 on 2018-09-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название филиала:')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес филиала:')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен:')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий:')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
    ]
