# Generated by Django 2.1.1 on 2018-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=300, verbose_name='Фраза на главной странице:')),
                ('tag', models.CharField(help_text='Главный теглайн', max_length=25, verbose_name='Главный тег')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Теглайн',
                'verbose_name_plural': 'Теглайны',
            },
        ),
    ]
