# Generated by Django 2.1.1 on 2018-09-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0004_auto_20180930_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='coordinates',
            field=models.CharField(default=None, help_text='Введите гео-координаты филиала вформате:60.0520376,30.334460.Взять в google', max_length=50, verbose_name='Координаты'),
        ),
    ]
