# Generated by Django 2.1.1 on 2018-09-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0005_auto_20180930_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagline',
            name='end_phrase',
            field=models.CharField(default=None, max_length=300, verbose_name='Конец фразы на главной странице:'),
        ),
    ]
