# Generated by Django 2.1.1 on 2018-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0011_auto_20180930_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagline',
            name='end_phrase',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Конец фразы на главной странице:'),
        ),
    ]
