# Generated by Django 2.1.1 on 2018-09-30 15:29

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0014_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('data_news', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен:')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цену', 'verbose_name_plural': 'Цены'},
        ),
    ]
