# Generated by Django 2.1.1 on 2018-09-30 15:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0015_auto_20180930_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(default=None, verbose_name='Текст'),
        ),
    ]
