# Generated by Django 2.1.1 on 2018-10-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0016_auto_20180930_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Фамилия Имя:')),
                ('tel', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона:')),
                ('avatar', models.ImageField(upload_to='teachers/', verbose_name='Аватар')),
                ('car_model', models.CharField(blank=True, max_length=30, null=True, verbose_name='Марка автомобиля')),
            ],
        ),
    ]
