# Generated by Django 2.1.1 on 2018-10-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0017_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Предподователь', 'verbose_name_plural': 'Предподователи'},
        ),
    ]
