# Generated by Django 2.1.1 on 2018-10-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0018_auto_20181003_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='tel',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='branches',
            name='phone',
            field=models.CharField(default='', max_length=25, verbose_name='Номер телефона:'),
        ),
    ]
