# Generated by Django 2.1.1 on 2018-10-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0019_auto_20181003_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='branches',
            name='lat',
            field=models.CharField(default=None, help_text='Введите гео-координаты филиала вформате:60.0520376.Взять в google', max_length=50, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='branches',
            name='lng',
            field=models.CharField(default=None, help_text='Введите гео-координаты филиала вформате:30.334460.Взять в google', max_length=50, verbose_name='Долгота'),
        ),
    ]
