# Generated by Django 2.1.1 on 2018-10-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0021_remove_branches_lat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='lng',
        ),
    ]
