# Generated by Django 2.1.1 on 2018-10-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0022_remove_branches_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='cordinates',
            field=models.CharField(default=None, help_text='Введите гео-координаты филиала вформате:30.334460.Взять в google', max_length=50, verbose_name='Долгота'),
        ),
    ]
