# Generated by Django 2.1.1 on 2018-10-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0023_branches_cordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='cordinates',
            new_name='lng',
        ),
        migrations.AddField(
            model_name='branches',
            name='lat',
            field=models.CharField(default=None, help_text='Введите гео-координаты филиала вформате:60.0520376.Взять в google', max_length=50, verbose_name='Широта'),
        ),
    ]
