# Generated by Django 2.1.1 on 2018-10-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0024_auto_20181006_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='tag',
            field=models.CharField(default=None, max_length=50, verbose_name='Тег'),
        ),
    ]
