# Generated by Django 2.1.1 on 2018-10-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0025_branches_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тег'),
        ),
    ]
