# Generated by Django 2.1.1 on 2018-10-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0026_auto_20181006_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='tag',
        ),
    ]
