# Generated by Django 2.1.1 on 2018-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0027_remove_branches_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250, verbose_name='Район города')),
                ('default_phone', models.CharField(max_length=25, verbose_name='Основной номер телефона:')),
                ('secondary_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Доп. номер телефона:')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='E-mail администратора')),
                ('vk_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на группу Вк')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на страницу Instagram')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
