# Generated by Django 2.1.1 on 2018-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0028_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен:'),
        ),
    ]
