# Generated by Django 2.1.1 on 2018-10-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0029_teachers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий:'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание:'),
        ),
    ]
