# Generated by Django 2.1.1 on 2018-10-06 20:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0030_auto_20181006_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание:'),
        ),
    ]
