# Generated by Django 2.1.1 on 2018-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0033_auto_20181007_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя клиента:')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail клиента')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон клиента')),
                ('is_processed', models.BooleanField(default='False', verbose_name='Обработана заявка')),
            ],
        ),
    ]
