# Generated by Django 2.1.1 on 2018-10-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0034_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
