# Generated by Django 2.1.1 on 2018-10-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0036_orders_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='branch',
            new_name='Филиал',
        ),
    ]
