# Generated by Django 2.1.1 on 2018-10-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0039_orders_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='location',
        ),
        migrations.AddField(
            model_name='contacts',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schooldriving.Branches'),
        ),
    ]
