# Generated by Django 2.1.1 on 2018-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0040_auto_20181007_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data_news',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
