# Generated by Django 2.1.1 on 2018-10-08 08:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0041_auto_20181008_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None, verbose_name='Текст'),
        ),
    ]
