# Generated by Django 2.1.1 on 2018-10-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0043_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
