# Generated by Django 2.1.2 on 2018-10-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0044_remove_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='phone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schooldriving.Contacts'),
        ),
    ]
