# Generated by Django 2.1.2 on 2018-10-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0045_auto_20181012_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='phone',
            field=models.CharField(default='', max_length=25, verbose_name='Номер телефона:'),
        ),
    ]
