# Generated by Django 2.1.2 on 2018-10-14 19:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0046_auto_20181012_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default=None, verbose_name='Текст')),
                ('icons', models.ImageField(upload_to='home_page/', verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен:')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
