# Generated by Django 2.1.2 on 2018-10-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0047_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Information',
        ),
    ]
