# Generated by Django 2.1.2 on 2018-10-20 09:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0048_auto_20181020_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок:')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default=None, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен:')),
            ],
        ),
    ]
