# Generated by Django 2.1.2 on 2018-10-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0049_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Реквизиты', 'verbose_name_plural': 'Реквизиты'},
        ),
    ]
