# Generated by Django 2.1.2 on 2018-10-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldriving', '0050_auto_20181020_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритет новости'),
        ),
    ]
